[functions.external-api]
verify_jwt = false

[functions.automation-worker]
verify_jwt = false

[functions.automation-incoming-webhook]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.website-builder]
enabled = true
verify_jwt = false
import_map = "./functions/website-builder/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/website-builder/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/website-builder/*.html" ]

[functions.website-agent]
verify_jwt = false

[functions.website-form-submit]
verify_jwt = false

[functions.website-public]
verify_jwt = false

[functions.website-export]
enabled = true
verify_jwt = false
import_map = "./functions/website-export/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/website-export/index.ts"

[functions.website-github-export]
enabled = true
verify_jwt = false
entrypoint = "./functions/website-github-export/index.ts"

[functions.github-oauth-callback]
enabled = true
verify_jwt = false
entrypoint = "./functions/github-oauth-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/website-export/*.html" ]

[functions.meta-oauth-callback]
enabled = true
verify_jwt = false
entrypoint = "./functions/meta-oauth-callback/index.ts"

[functions.meta-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/meta-webhook/index.ts"
