[functions.external-api]
verify_jwt = false

[functions.automation-worker]
verify_jwt = false

[functions.automation-incoming-webhook]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false
