export interface ProductKnowledgeEntry {
  id: string;
  category:
    | "Finance"
    | "Human Resources"
    | "Marketing"
    | "Global Platform"
    | "Workspace";
  name: string;
  purpose: string;
  features: string[];
  subviews: string[];
  workflow: string[];
  importantActions: string[];
  commonQuestions: string[];
  relationships: string[];
  keywords: string[];
}

const entry = (
  id: string,
  category: ProductKnowledgeEntry["category"],
  name: string,
  purpose: string,
  features: string[],
  subviews: string[],
  workflow: string[],
  importantActions: string[],
  commonQuestions: string[],
  relationships: string[],
  keywords: string[],
): ProductKnowledgeEntry => ({
  id,
  category,
  name,
  purpose,
  features,
  subviews,
  workflow,
  importantActions,
  commonQuestions,
  relationships,
  keywords,
});

export const NEXTAURA_PRODUCT_KNOWLEDGE: ProductKnowledgeEntry[] = [
  entry(
    "invoicing",
    "Finance",
    "Invoicing",
    "Create and manage customer invoices from draft through payment.",
    [
      "Multi-currency invoices",
      "Customer records",
      "Line items and tax",
      "Receivable status",
    ],
    ["Invoices", "Create invoice", "Customers"],
    [
      "Create or select a customer",
      "Add invoice items",
      "Review totals",
      "Save and update status",
    ],
    ["Create invoice", "Open customers", "Mark an invoice paid"],
    [
      "How do I create an invoice?",
      "Which invoices are overdue?",
      "Who owes us money?",
    ],
    ["Contacts can become customers", "Paid invoices inform accounting"],
    ["invoice", "customer", "receivable", "overdue", "payment"],
  ),
  entry(
    "accounting",
    "Finance",
    "Accounting",
    "Maintain journals, the general ledger, reconciliation, and financial reports.",
    [
      "Double-entry journals",
      "Chart of accounts",
      "Ledger",
      "Bank reconciliation",
      "Reports",
    ],
    [
      "Accounting",
      "General ledger",
      "Journal entry",
      "Bank reconciliation",
      "Financial reports",
    ],
    [
      "Review accounts",
      "Post balanced entries",
      "Reconcile bank activity",
      "Run reports",
    ],
    ["Create journal entry", "Open ledger", "Reconcile transaction"],
    [
      "How do journals work?",
      "Where is the ledger?",
      "How do I reconcile a transaction?",
    ],
    ["Invoices, expenses, and payroll can create accounting activity"],
    ["accounting", "ledger", "journal", "reconciliation", "account"],
  ),
  entry(
    "expenses",
    "Finance",
    "Expenses",
    "Capture employee spend and move expense records through review and reimbursement.",
    ["Expense records", "Receipts", "Approval status", "Corporate cards"],
    ["Expenses", "Approval queue", "Corporate cards"],
    [
      "Submit expense",
      "Review policy details",
      "Approve or reject",
      "Reimburse",
    ],
    ["Submit expense", "Review approvals", "Open corporate cards"],
    ["Which expenses need review?", "How do I submit an expense?"],
    ["Approved expenses inform accounting", "Approvals centralizes decisions"],
    ["expense", "merchant", "receipt", "reimbursement", "card"],
  ),
  entry(
    "sign",
    "Finance",
    "NextAura Sign",
    "Prepare documents, assign recipients, and track electronic signatures.",
    [
      "Document preparation",
      "Recipients and fields",
      "Status tracking",
      "Audit trail",
    ],
    ["Documents", "Prepare agreement", "Signer experience"],
    [
      "Upload or prepare document",
      "Place fields",
      "Assign recipients",
      "Send and monitor",
    ],
    ["Prepare agreement", "Open document", "Review signature status"],
    ["How do I send an agreement?", "Who still needs to sign?"],
    [
      "Contacts provide signatories",
      "Completed agreements belong in Documents",
    ],
    ["sign", "signature", "agreement", "recipient", "document"],
  ),
  entry(
    "equity",
    "Finance",
    "Equity",
    "Maintain shareholders, ownership records, option grants, and dilution scenarios.",
    ["Cap table", "Share classes", "Option grants", "Dilution modelling"],
    ["Equity overview", "Shareholders", "Dilution simulator"],
    ["Review ownership", "Add or update holders", "Model a financing scenario"],
    ["Open cap table", "Add shareholder", "Model dilution"],
    ["Who owns the company?", "How will a round affect dilution?"],
    [
      "Employee options relate to Employees",
      "Investor contacts relate to Contacts",
    ],
    ["equity", "shares", "shareholder", "cap table", "dilution"],
  ),
  entry(
    "esg",
    "Finance",
    "ESG & Carbon",
    "Record sustainability activity and calculate organizational emissions.",
    [
      "Scope 1–3 records",
      "Emission factors",
      "Carbon activity",
      "ESG reporting",
    ],
    ["ESG records", "Carbon calculator"],
    [
      "Record an activity",
      "Classify its scope",
      "Calculate CO2e",
      "Review reports",
    ],
    ["Add carbon activity", "Open carbon calculator"],
    ["How do I record emissions?", "What are Scope 1, 2, and 3?"],
    ["Expense and fleet activity can support carbon records"],
    ["esg", "carbon", "emission", "sustainability", "scope"],
  ),

  entry(
    "employees",
    "Human Resources",
    "Employees",
    "Keep the employee directory, profiles, departments, and reporting hierarchy.",
    [
      "Employee profiles",
      "Departments",
      "Manager hierarchy",
      "Avatar management",
      "Organization chart",
    ],
    ["Employee directory", "Employee detail", "Organization chart"],
    [
      "Create department if needed",
      "Add employee",
      "Assign manager",
      "Maintain profile",
    ],
    ["Add employee", "Create department", "Open organization chart"],
    [
      "How do I add an employee?",
      "Who works in a department?",
      "How do managers work?",
    ],
    [
      "Attendance, time off, appraisals, fleet, and payroll use employee records",
    ],
    ["employee", "people", "department", "manager", "team", "org chart"],
  ),
  entry(
    "attendance",
    "Human Resources",
    "Attendance",
    "Track daily clock state, breaks, work location, and attendance records.",
    ["Clock in/out", "Break tracking", "Kiosk mode", "Attendance log"],
    ["Today", "Attendance log", "Kiosk"],
    ["Clock in", "Start or end break", "Clock out", "Review daily records"],
    ["Clock in", "Open kiosk", "Review attendance"],
    ["Who is absent today?", "How do I clock in?", "Who is working remotely?"],
    ["Uses Employees", "Approved leave explains attendance status"],
    ["attendance", "absent", "clock", "break", "remote", "working"],
  ),
  entry(
    "recruitment",
    "Human Resources",
    "Recruitment",
    "Manage job openings and move candidates through the hiring pipeline.",
    ["Job openings", "Candidate pipeline", "Interviews", "Offers", "Hiring"],
    ["Candidates", "Pipeline", "Job openings"],
    [
      "Create opening",
      "Add candidate",
      "Move stages",
      "Interview",
      "Offer and hire",
    ],
    ["Create opening", "Add candidate", "Move candidate", "Hire candidate"],
    ["Which candidates are active?", "How do I hire a candidate?"],
    ["Hiring creates an Employee record", "Interviews can appear in Calendar"],
    ["recruitment", "candidate", "job", "opening", "interview", "hire"],
  ),
  entry(
    "time_off",
    "Human Resources",
    "Time Off",
    "Manage employee leave requests, decisions, and team availability.",
    ["Leave requests", "Approval flow", "Team leave calendar"],
    ["Requests", "Pending approvals", "Team calendar"],
    [
      "Submit request",
      "Manager reviews",
      "Approve or reject",
      "Calendar updates",
    ],
    ["Request leave", "Review request", "Open leave calendar"],
    ["Which requests are pending?", "Who is on leave?"],
    ["Approved leave connects to Attendance and Calendar"],
    ["leave", "time off", "vacation", "request", "absence"],
  ),
  entry(
    "appraisals",
    "Human Resources",
    "Appraisals",
    "Run review cycles and track employee goals and feedback.",
    ["Review cycles", "Self review", "Manager review", "Goals and OKRs"],
    ["Appraisals", "Goals and OKRs"],
    [
      "Create cycle",
      "Collect self review",
      "Collect manager review",
      "Complete appraisal",
    ],
    ["Create review cycle", "Submit review", "Open goals"],
    ["Which reviews are pending?", "How do I complete an appraisal?"],
    ["Uses Employees and manager hierarchy"],
    ["appraisal", "review", "performance", "goal", "okr"],
  ),
  entry(
    "fleet",
    "Human Resources",
    "Fleet",
    "Maintain company vehicles, assignments, mileage, and service records.",
    [
      "Vehicle directory",
      "Employee assignment",
      "Odometer",
      "Maintenance schedule",
    ],
    ["Vehicles", "Maintenance"],
    [
      "Add vehicle",
      "Assign employee",
      "Record maintenance",
      "Plan next service",
    ],
    ["Add vehicle", "Log maintenance"],
    ["Which vehicles need service?", "Who has a vehicle assigned?"],
    ["Assignments use Employees", "Costs may become Expenses"],
    ["fleet", "vehicle", "car", "maintenance", "odometer"],
  ),
  entry(
    "payroll",
    "Human Resources",
    "Payroll",
    "Prepare payroll runs, calculate employee payslips, approve, and post totals.",
    [
      "Payroll runs",
      "Gross-to-net calculation",
      "Payslips",
      "Approval",
      "GL synchronization",
    ],
    ["Payroll runs", "Run detail", "Payslips"],
    [
      "Create draft run",
      "Review employee calculations",
      "Approve run",
      "Post accounting entry",
    ],
    ["Create payroll run", "Review payslips", "Approve payroll"],
    [
      "Which runs are drafts?",
      "How is net pay calculated?",
      "How do I approve payroll?",
    ],
    ["Uses employee compensation", "Approved payroll can post to Accounting"],
    ["payroll", "payslip", "salary", "net pay", "gross pay", "deduction"],
  ),

  entry(
    "email_marketing",
    "Marketing",
    "Email Marketing",
    "Create email campaigns and reusable templates for workspace contacts.",
    [
      "Campaigns",
      "Templates",
      "Audience selection",
      "Scheduling",
      "Delivery results",
    ],
    ["Campaigns", "Create campaign", "Templates"],
    ["Choose template", "Write message", "Select audience", "Schedule or send"],
    ["Create campaign", "Open templates"],
    ["How do I create a campaign?", "Which campaigns are scheduled?"],
    [
      "Uses Contacts for audiences",
      "Scheduled campaigns can appear in Calendar",
    ],
    ["email", "campaign", "template", "audience", "newsletter"],
  ),
  entry(
    "sms_marketing",
    "Marketing",
    "SMS Marketing",
    "Create concise mobile broadcasts and monitor delivery.",
    ["Broadcasts", "Audience selection", "Scheduling", "Delivery results"],
    ["Broadcasts", "Create broadcast"],
    ["Write message", "Select audience", "Review recipient count", "Schedule"],
    ["Create broadcast", "Open broadcasts"],
    ["Which broadcasts are scheduled?", "How do I create an SMS?"],
    ["Uses Contacts for audiences"],
    ["sms", "broadcast", "text message", "campaign"],
  ),
  entry(
    "surveys",
    "Marketing",
    "Surveys",
    "Build feedback forms and review submitted responses.",
    [
      "Survey builder",
      "Question types",
      "Response collection",
      "Feedback summaries",
    ],
    ["Surveys", "Responses", "Create survey"],
    ["Create survey", "Add questions", "Publish", "Review responses"],
    ["Create survey", "Review responses"],
    ["How do I create a survey?", "How many responses arrived?"],
    ["Can target Contacts", "Insights may be reviewed in Analytics"],
    ["survey", "response", "feedback", "csat", "nps", "form"],
  ),
  entry(
    "social_marketing",
    "Marketing",
    "Social Marketing",
    "Compose and schedule posts across connected social channels.",
    ["Connected accounts", "Post composer", "Scheduling", "Post status"],
    ["Posts", "Scheduled", "Create post", "Accounts"],
    ["Connect account", "Compose post", "Select channels", "Schedule"],
    ["Create post", "Open scheduled posts"],
    ["What is scheduled?", "How do I create a post?"],
    ["Scheduled posts can appear in Calendar"],
    ["social", "post", "schedule", "linkedin", "facebook", "instagram"],
  ),

  entry(
    "contacts",
    "Global Platform",
    "Contacts",
    "Maintain shared customer, vendor, partner, and lead records.",
    ["Contact directory", "Roles", "Company details", "Business relationships"],
    ["Contacts", "Contact detail"],
    ["Add contact", "Assign roles", "Use the record in related apps"],
    ["Add contact", "Find contact"],
    ["How do I add a customer?", "Where are vendors stored?"],
    ["Feeds Invoicing, Sign, Marketing, and Equity"],
    ["contact", "customer", "vendor", "partner", "lead"],
  ),
  entry(
    "documents",
    "Global Platform",
    "Documents",
    "Organize and find workspace files and business records.",
    [
      "Document library",
      "Categories",
      "Search",
      "Version-oriented organization",
    ],
    ["Documents", "Search"],
    ["Add document", "Categorize", "Find and open"],
    ["Open document vault", "Search documents"],
    ["Where should I store a document?", "How do I find a file?"],
    ["Stores supporting files from Sign, Expenses, HR, and Finance"],
    ["document", "file", "vault", "search", "folder"],
  ),
  entry(
    "calendar",
    "Global Platform",
    "Calendar",
    "See workspace events generated by business workflows in one schedule.",
    ["Cross-module events", "Event creation", "Dates and attendees"],
    ["Calendar"],
    ["Create or receive event", "Review schedule", "Open related module"],
    ["Create event", "Open calendar"],
    ["What is coming up?", "How are workflow dates added?"],
    ["Receives leave, payroll, interviews, appraisals, and campaign dates"],
    ["calendar", "event", "schedule", "meeting", "date"],
  ),
  entry(
    "approvals",
    "Global Platform",
    "Approvals",
    "Centralize decisions waiting across business applications.",
    ["Pending queue", "Module context", "Approval status"],
    ["Approvals"],
    ["Open request", "Review source record", "Approve or reject in its module"],
    ["Review approvals"],
    ["What needs approval?", "Where did a request originate?"],
    ["Aggregates Expenses, Time Off, Payroll, Recruitment, Sign, and ESG"],
    ["approval", "pending", "review", "decision"],
  ),
  entry(
    "analytics",
    "Global Platform",
    "Analytics",
    "Explore cross-module trends after operational records exist.",
    ["Cross-module reporting", "Operational trends", "Record-based analysis"],
    ["Analytics"],
    ["Choose a dataset", "Review trends", "Return to source records"],
    ["Open analytics"],
    ["Where can I analyze trends?", "Why is a report empty?"],
    ["Summarizes data from enabled apps without replacing record workflows"],
    ["analytics", "report", "trend", "metric", "insight"],
  ),

  entry(
    "organizations",
    "Workspace",
    "Organizations and workspaces",
    "Separate each company into an isolated tenant workspace.",
    [
      "Organization switcher",
      "Memberships",
      "Tenant isolation",
      "Base currency",
    ],
    ["Workspace switcher", "Settings"],
    [
      "Join or create workspace",
      "Select active workspace",
      "Work only with that tenant context",
    ],
    ["Switch workspace", "Open settings"],
    [
      "Can I manage more than one company?",
      "What changes when I switch workspaces?",
    ],
    [
      "Every business record and service entitlement belongs to one organization",
    ],
    ["organization", "workspace", "tenant", "company", "switch"],
  ),
  entry(
    "roles",
    "Workspace",
    "Roles and permissions",
    "Control what each member may see or do in a workspace.",
    ["Membership role", "Module permissions", "RLS-backed data access"],
    ["Settings"],
    [
      "Invite or identify member",
      "Assign role",
      "Enforce access in UI, API, and database",
    ],
    ["Open settings"],
    ["Can an employee see payroll?", "How are permissions enforced?"],
    ["NextAura AI follows the same role and tenant scope"],
    ["role", "permission", "rbac", "access", "security"],
  ),
  entry(
    "services",
    "Workspace",
    "Service selection",
    "Enable only the NextAura applications an organization needs.",
    ["Service catalog", "Organization entitlements", "Activation workflow"],
    ["Apps", "Add services"],
    [
      "Open service selection",
      "Choose apps",
      "Confirm activation",
      "Return to Apps",
    ],
    ["Add services", "Open Apps"],
    ["What services are enabled?", "How do I add an app?"],
    ["Controls which Finance, HR, and Marketing apps appear"],
    ["service", "app", "enable", "activate", "entitlement"],
  ),
  entry(
    "pricing",
    "Workspace",
    "Plans and pricing",
    "Explain the three NextAura subscription structures without creating a payment.",
    [
      "Monthly and yearly billing display",
      "One App Free",
      "Standard",
      "Custom",
    ],
    ["Pricing", "Settings and plans"],
    [
      "Compare plans",
      "Choose billing cycle",
      "Select a plan",
      "Continue to the controlled next step",
    ],
    ["Open pricing", "Choose services"],
    [
      "What is the difference between Standard and Custom?",
      "How much is yearly billing?",
    ],
    [
      "One App Free includes one app and unlimited users; Standard includes all core apps; Custom adds customization, multi-company, API, and advanced automation",
    ],
    ["pricing", "plan", "standard", "custom", "free", "monthly", "yearly"],
  ),
  entry(
    "navigation",
    "Workspace",
    "Navigation and common workflows",
    "Move directly from an application to its records, actions, and details.",
    ["Sidebar apps", "Global search", "Breadcrumbs", "Contextual actions"],
    ["Workspace Home", "Apps", "Global search"],
    ["Open an app", "Find a record", "Take an action", "Review details"],
    ["Search workspace", "Browse Apps", "Open NextAura AI"],
    ["How do I find an app?", "How do I get back home?"],
    ["Navigation respects active services and the current organization"],
    ["navigation", "search", "sidebar", "home", "workflow"],
  ),
];

const normalize = (value: string) => value.toLowerCase();

export const findRelevantKnowledge = (
  query: string,
  limit = 8,
): ProductKnowledgeEntry[] => {
  const normalized = normalize(query);
  const scored = NEXTAURA_PRODUCT_KNOWLEDGE.map((item) => {
    const terms = [item.id, item.name, item.category, ...item.keywords].map(
      normalize,
    );
    const score = terms.reduce(
      (total, term) => total + (normalized.includes(term) ? 2 : 0),
      0,
    );
    return { item, score };
  }).sort((a, b) => b.score - a.score);

  const matches = scored
    .filter(({ score }) => score > 0)
    .slice(0, limit)
    .map(({ item }) => item);
  if (matches.length > 0) return matches;
  return NEXTAURA_PRODUCT_KNOWLEDGE.filter((item) =>
    ["navigation", "services", "organizations", "pricing"].includes(item.id),
  );
};

export const serializeKnowledge = (entries: ProductKnowledgeEntry[]): string =>
  JSON.stringify(
    entries.map((item) => ({
      id: item.id,
      category: item.category,
      name: item.name,
      purpose: item.purpose,
      features: item.features,
      subviews: item.subviews,
      workflow: item.workflow,
      importantActions: item.importantActions,
      commonQuestions: item.commonQuestions,
      relationships: item.relationships,
    })),
  );
