import { useEffect, useState } from 'react';
import { CheckCircle2, CircleAlert, Link2, Loader2, Pencil, Plus, RotateCcw, Trash2, X } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { entitlementService, type PlanEntitlements } from '../../services/entitlementService';
import { integrationConnectionService, type IntegrationConnection } from '../../services/integrationConnectionService';

const providerLabel: Record<IntegrationConnection['provider'], string> = { generic_api: 'Generic API', google: 'Google', github: 'GitHub', slack: 'Slack', meta: 'WhatsApp / Meta' };
const statusStyle: Record<IntegrationConnection['status'], string> = { active: 'bg-emerald-50 text-emerald-700', expired: 'bg-amber-50 text-amber-700', revoked: 'bg-slate-100 text-slate-600', error: 'bg-rose-50 text-rose-700' };
const date = (value: string | null) => value ? new Date(value).toLocaleDateString() : '—';

export function ConnectionsPanel() {
  const { currentOrg, navigate } = useApp();
  const [connections, setConnections] = useState<IntegrationConnection[]>([]);
  const [entitlements, setEntitlements] = useState<PlanEntitlements | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [formOpen, setFormOpen] = useState(false); const [busy, setBusy] = useState(false); const [addChoice, setAddChoice] = useState<'menu' | 'generic'>('menu');
  const [name, setName] = useState(''); const [baseUrl, setBaseUrl] = useState(''); const [secret, setSecret] = useState('');
  const canManage = ['Owner', 'Admin', 'Administrator'].includes(currentOrg.membershipRole || '');
  const allowed = Boolean(entitlements?.access_active && entitlements.automation_access);
  const load = async () => { const organizationId = currentOrg.id; setLoading(true); setError(''); setConnections([]); try { const [items, plan] = await Promise.all([integrationConnectionService.list(organizationId), entitlementService.getPlanEntitlements(organizationId)]); if (currentOrg.id === organizationId) { setConnections(items); setEntitlements(plan); } } catch (e: any) { if (currentOrg.id === organizationId) setError(e.message || 'Unable to load connections.'); } finally { if (currentOrg.id === organizationId) setLoading(false); } };
  useEffect(() => { void load(); }, [currentOrg.id]);
  const mutate = async (operation: () => Promise<any>, success?: string) => { try { setBusy(true); setError(''); await operation(); if (success) setError(success); await load(); } catch (e: any) { setError(e.message || 'Unable to update connection.'); } finally { setBusy(false); } };
  const create = async (event: React.FormEvent) => { event.preventDefault(); await mutate(async () => { await integrationConnectionService.createGenericApi(currentOrg.id, name, baseUrl, secret); setName(''); setBaseUrl(''); setSecret(''); setFormOpen(false); }, 'Connection saved. Its secret is not stored in the browser.'); };
  const connectGoogle = async (connectionId?: string) => { try { setBusy(true); const result = await integrationConnectionService.startGoogleOAuth(currentOrg.id, connectionId); window.location.assign(result.authorizationUrl); } catch (e: any) { setError(e.message || 'Unable to start Google connection.'); setBusy(false); } };
  const connectGithub = async (connectionId?: string) => { try { setBusy(true); const result = await integrationConnectionService.startGithubOAuth(currentOrg.id, connectionId); window.location.assign(result.authorizationUrl); } catch (e: any) { setError(e.message || 'Unable to start GitHub connection.'); setBusy(false); } };
  useEffect(() => { const params = new URLSearchParams(window.location.search); const result = params.get('github'); if (!result) return; params.delete('github'); window.history.replaceState({}, '', `${window.location.pathname}${params.size ? `?${params}` : ''}${window.location.hash}`); setError(result === 'connected' ? 'GitHub connected successfully.' : 'GitHub connection could not be completed. Try again.'); if (result === 'connected') void load(); }, []);
  if (loading) return <section className="mt-6 rounded-2xl border border-slate-200 p-6"><div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" />Loading connections…</div></section>;
  if (!allowed) return <section className="mt-6 rounded-2xl border border-blue-200 bg-blue-50 p-6"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 h-5 w-5 text-blue-700" /><div><h2 className="font-semibold text-slate-900">Connections are available on Custom</h2><p className="mt-1 text-sm text-slate-600">Upgrade to securely connect external services to automation workflows.</p><button onClick={() => navigate('pricing')} className="mt-4 rounded-lg bg-blue-700 px-3 py-2 text-sm font-semibold text-white">View Custom plan</button></div></div></section>;
  return <section className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-900">Connections</h2><p className="text-sm text-slate-500">Organization-scoped credentials for future integration nodes.</p></div>{canManage && <button onClick={() => { setAddChoice('menu'); setFormOpen(true); }} className="inline-flex items-center gap-2 rounded-lg bg-blue-700 px-3 py-2 text-sm font-semibold text-white"><Plus className="h-4 w-4" />Add connection</button>}</div>
    {error && <p role="alert" className={`mt-4 rounded-lg px-3 py-2 text-sm ${error.includes('saved') || error.includes('successful') ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{error}</p>}
    {formOpen && <div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Add connection</h3><p className="text-xs text-slate-500">Credentials stay encrypted on the server.</p></div><button type="button" onClick={() => setFormOpen(false)} aria-label="Close"><X className="h-4 w-4" /></button></div>{addChoice === 'menu' ? <div className="mt-4 grid gap-3 sm:grid-cols-2"><button disabled={busy} onClick={() => void connectGoogle()} className="rounded-xl border border-blue-200 bg-white p-4 text-left hover:border-blue-400"><b className="block text-slate-900">Connect Google</b><span className="mt-1 block text-xs text-slate-500">Google account identity only. Gmail, Sheets, Calendar and Drive actions remain unavailable.</span></button><button disabled={busy} onClick={() => void connectGithub()} className="rounded-xl border border-slate-200 bg-white p-4 text-left hover:border-blue-400"><b className="block text-slate-900">Connect GitHub</b><span className="mt-1 block text-xs text-slate-500">Connect your GitHub account to export NextAura websites directly to repositories.</span></button><button onClick={() => setAddChoice('generic')} className="rounded-xl border border-slate-200 bg-white p-4 text-left hover:border-blue-400"><b className="block text-slate-900">Generic API</b><span className="mt-1 block text-xs text-slate-500">Store an API base URL and token securely.</span></button><p className="text-xs text-slate-500 sm:col-span-2">Slack and WhatsApp / Meta are coming soon.</p></div> : <form onSubmit={create} className="mt-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Connection name<input required maxLength={120} value={name} onChange={e => setName(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2" placeholder="Partner API" /></label><label className="text-sm font-medium">API base URL<input required type="url" value={baseUrl} onChange={e => setBaseUrl(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2" placeholder="https://api.example.com" /></label></div><label className="mt-3 block text-sm font-medium">Secret / API token<input required type="password" autoComplete="new-password" value={secret} onChange={e => setSecret(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2" /></label><p className="mt-2 text-xs text-amber-700">This secret cannot be viewed again after saving.</p><button disabled={busy} className="mt-4 rounded-lg bg-blue-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">Save connection</button></form>}</div>}
    <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200">{connections.length ? connections.map(connection => <article key={connection.id} className="flex flex-col gap-3 border-b border-slate-100 p-4 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="rounded-xl bg-blue-50 p-2 text-blue-700"><Link2 className="h-4 w-4" /></span><div className="min-w-0"><p className="font-medium text-slate-900">{connection.name}</p><p className="truncate text-xs text-slate-500">{providerLabel[connection.provider]} · {connection.account_label || 'No account label'} · Created {date(connection.created_at)}{connection.last_verified_at ? ` · Verified ${date(connection.last_verified_at)}` : ''}</p></div></div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs font-medium capitalize ${statusStyle[connection.status]}`}>{connection.status}</span>{canManage && <>{connection.provider === 'google' && <button disabled={busy} onClick={() => void connectGoogle(connection.id)} title="Reconnect Google" className="rounded p-2 text-slate-500 hover:bg-slate-100"><Link2 className="h-4 w-4" /></button>}<button disabled={busy} onClick={() => { const next = prompt('Connection name', connection.name); if (next && next.trim() && next.trim() !== connection.name) void mutate(() => integrationConnectionService.rename(currentOrg.id, connection.id, next.trim())); }} title="Rename" className="rounded p-2 text-slate-500 hover:bg-slate-100"><Pencil className="h-4 w-4" /></button><button disabled={busy || connection.status !== 'active'} onClick={() => void mutate(() => integrationConnectionService.test(currentOrg.id, connection.id), 'Connection successful.')} title="Test" className="rounded p-2 text-slate-500 hover:bg-slate-100"><CheckCircle2 className="h-4 w-4" /></button>{connection.status === 'active' && <button disabled={busy} onClick={() => confirm('Revoke this connection? It can no longer be selected.') && void mutate(() => integrationConnectionService.revoke(currentOrg.id, connection.id))} title="Revoke" className="rounded p-2 text-slate-500 hover:bg-slate-100"><RotateCcw className="h-4 w-4" /></button>}<button disabled={busy} onClick={() => confirm('Delete this connection? It will be revoked and removed from selectors.') && void mutate(() => integrationConnectionService.remove(currentOrg.id, connection.id))} title="Delete" className="rounded p-2 text-rose-600 hover:bg-rose-50"><Trash2 className="h-4 w-4" /></button></>}</div></article>) : <div className="p-8 text-center"><p className="text-sm font-medium text-slate-700">No connections yet</p><p className="mt-1 text-sm text-slate-500">Connect Google or add a Generic API connection.</p>{canManage && <button onClick={() => { setAddChoice('menu'); setFormOpen(true); }} className="mt-4 text-sm font-semibold text-blue-700">+ Add connection</button>}</div>}</div>
  </section>;
}
