import { useCallback, useState } from 'react';
import { ReactFlow, Background, Controls, MiniMap, addEdge, useEdgesState, useNodesState, type Connection, type Edge, type Node } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { Bell, BriefcaseBusiness, ChevronLeft, Contact, GitBranch, Plus, Send, Trash2, UserPlus, Webhook } from 'lucide-react';

type BuilderNode = Node<any>;
const palette = [['Employee Created','Trigger','Starts when an employee is created',UserPlus],['Contact Created','Trigger','Starts when a contact is created',Contact],['Expense Status Changed','Trigger','Starts when expense status changes',BriefcaseBusiness],['Incoming Webhook','Trigger','Starts from a secured webhook',Webhook],['IF','Logic','Evaluate a condition',GitBranch],['Create Notification','Action','Notify workspace members',Bell],['Send Webhook','Action','Send an HTTPS POST request',Send]] as const;
export function WorkflowBuilder({ onClose }: { onClose: () => void }) {
  const [nodes,setNodes,onNodesChange]=useNodesState<BuilderNode>([{id:'trigger',position:{x:80,y:160},data:{title:'Employee Created',category:'Trigger',summary:'Starts when an employee is created'}},{id:'action',position:{x:400,y:160},data:{title:'Create Notification',category:'Action',summary:'Notify workspace members'}}]); const [edges,setEdges,onEdgesChange]=useEdgesState<Edge>([{id:'trigger-action',source:'trigger',target:'action',animated:true}]); const [selected,setSelected]=useState<BuilderNode|null>(null);
  const onConnect=useCallback((connection:Connection)=>setEdges(current=>addEdge({...connection,animated:true},current)),[setEdges]); const add=(item:typeof palette[number])=>setNodes(current=>[...current,{id:crypto.randomUUID(),position:{x:140+current.length*40,y:80+current.length*55},data:{title:item[0],category:item[1],summary:item[2]}}]);
  return <div className="fixed inset-0 z-[70] flex bg-slate-950/30 p-3 backdrop-blur-sm md:p-6"><div className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-2xl border bg-white shadow-2xl dark:bg-slate-900"><header className="flex items-center justify-between border-b p-3"><div className="flex items-center gap-3"><button onClick={onClose} aria-label="Close workflow builder" className="rounded-lg p-2 hover:bg-slate-100"><ChevronLeft className="h-5 w-5"/></button><div><b>Visual workflow builder</b><p className="text-xs text-slate-500">Canvas foundation — saving arrives later.</p></div></div><div className="flex gap-2"><button disabled className="rounded-lg border px-3 py-2 text-xs opacity-60">Test</button><button disabled className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-semibold text-white opacity-60">Save</button></div></header><div className="grid min-h-0 flex-1 grid-cols-[220px_1fr_280px]"><aside className="overflow-auto border-e p-3"><p className="mb-3 text-xs font-semibold uppercase text-slate-500">Node palette</p>{palette.map(item=>{const Icon=item[3];return <button key={item[0]} onClick={()=>add(item)} className="mb-2 flex w-full items-start gap-2 rounded-xl border p-2 text-left hover:border-blue-300 hover:bg-blue-50"><Icon className="mt-0.5 h-4 w-4 text-blue-600"/><span><b className="block text-xs">{item[0]}</b><span className="text-[11px] text-slate-500">{item[1]}</span></span><Plus className="ms-auto h-3.5 w-3.5"/></button>})}</aside><main className="min-w-0"><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={(_,n: Node)=>setSelected(n as BuilderNode)} onPaneClick={()=>setSelected(null)} fitView><Background gap={18}/><Controls/><MiniMap/></ReactFlow></main><aside className="overflow-auto border-s p-4"><p className="text-xs font-semibold uppercase text-slate-500">Configuration</p>{selected?<div className="mt-4 space-y-3"><div className="rounded-xl bg-slate-50 p-3"><b>{selected.data.title}</b><p className="mt-1 text-xs text-slate-500">{selected.data.category} · {selected.data.summary}</p></div><p className="rounded border p-2 text-xs text-slate-500">Configuration controls arrive with persistence.</p><button onClick={()=>{setNodes(ns=>ns.filter(n=>n.id!==selected.id));setEdges(es=>es.filter(e=>e.source!==selected.id&&e.target!==selected.id));setSelected(null)}} className="inline-flex items-center gap-2 text-sm text-red-600"><Trash2 className="h-4 w-4"/>Delete node</button></div>:<p className="mt-4 text-sm text-slate-500">Select a node to configure it.</p>}</aside></div></div></div>;
}
