import { authenticate, corsHeaders, json, requireBillingAdmin } from '../_shared/billing.ts';
import { getOrganizationEntitlements } from '../_shared/entitlements.ts';

const allowedSections = new Set(['hero', 'text', 'image', 'button_group', 'spacer']);
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === 'object' && !Array.isArray(value);
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 63);

function validateDocument(value: unknown) {
  if (!isRecord(value) || value.version !== 1 || !Array.isArray(value.sections) || value.sections.length > 100 || new TextEncoder().encode(JSON.stringify(value)).length > 262144) throw new Error('Website document is invalid.');
  const ids = new Set<string>();
  for (const section of value.sections) {
    if (!isRecord(section) || typeof section.id !== 'string' || !section.id || section.id.length > 80 || ids.has(section.id) || !allowedSections.has(String(section.type)) || !isRecord(section.props ?? {}) || !isRecord(section.style ?? {}) || Object.keys(section.props ?? {}).length > 40 || Object.keys(section.style ?? {}).length > 40) throw new Error('Website document contains an invalid section.');
    if (/<\/?script|on[a-z]+\s*=|javascript:|<iframe/i.test(JSON.stringify(section)) || JSON.stringify(section).length > 16384) throw new Error('Website document contains unsupported content.');
    ids.add(section.id);
  }
  return value;
}
async function authorize(admin: any, userId: string, organizationId: string, mutate: boolean) {
  if (!organizationId) throw new Error('organizationId is required.');
  if (mutate) await requireBillingAdmin(admin, userId, organizationId);
  else { const { data } = await admin.from('organization_members').select('id').eq('organization_id', organizationId).eq('user_id', userId).eq('status', 'Active').maybeSingle(); if (!data) throw new Error('You do not have access to this organization.'); }
  const entitlements: any = await getOrganizationEntitlements(admin, organizationId);
  if (!entitlements.access_active || !entitlements.website_builder_access) throw new Error('Website Builder is not available for this organization.');
  const { data: service } = await admin.from('organization_services').select('service_key').eq('organization_id', organizationId).eq('service_key', 'website_builder').eq('status', 'active').maybeSingle();
  if (!service) throw new Error('Activate Website Builder in Services before creating or viewing websites.');
  return entitlements;
}
async function audit(admin: any, organizationId: string, userId: string, action: string, details: Record<string, unknown>) { await admin.from('audit_logs').insert({ organization_id: organizationId, user_name: userId, action, details: JSON.stringify(details) }); }

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });
  try {
    const { admin, user } = await authenticate(req); const body = await req.json(); const operation = String(body.operation || ''); const organizationId = String(body.organizationId || '');
    const mutate = ['createSite', 'updateSite', 'archiveSite', 'createPage', 'updatePageMetadata', 'savePageDocument'].includes(operation); const entitlements = await authorize(admin, user.id, organizationId, mutate);
    if (operation === 'listSites') { const { data, error } = await admin.from('website_sites').select('id,name,slug,status,default_locale,updated_at,created_at,website_pages(count)').eq('organization_id', organizationId).is('archived_at', null).order('updated_at', { ascending: false }); if (error) throw error; return json({ success: true, sites: data || [] }); }
    if (operation === 'getSite') { const { data, error } = await admin.from('website_sites').select('id,name,slug,status,default_locale,updated_at,created_at,website_pages(id,name,slug,page_type,is_homepage,updated_at)').eq('id', body.siteId).eq('organization_id', organizationId).maybeSingle(); if (error || !data) return json({ success: false, error: 'Website not found.' }, 404); return json({ success: true, site: data }); }
    if (operation === 'createSite') { const name = String(body.name || '').trim(); const rawSlug = body.slug ? String(body.slug) : slugify(name); const slug = slugify(rawSlug); if (!name || name.length > 120 || !slug || slug !== rawSlug) return json({ success: false, error: 'Enter a name and lowercase URL-safe slug.' }, 400); const { count, error: countError } = await admin.from('website_sites').select('id', { count: 'exact', head: true }).eq('organization_id', organizationId).is('archived_at', null); if (countError) throw countError; if (entitlements.website_site_limit !== null && count! >= entitlements.website_site_limit) return json({ success: false, error: 'Your plan has reached its Website Builder site limit.' }, 409); const { data: site, error } = await admin.from('website_sites').insert({ organization_id: organizationId, name, slug, created_by: user.id }).select('*').single(); if (error) throw error; const document = { version: 1, sections: [] }; const { data: page, error: pageError } = await admin.from('website_pages').insert({ organization_id: organizationId, site_id: site.id, name: 'Home', slug: '/', page_type: 'home', is_homepage: true, draft_document: document, created_by: user.id }).select('*').single(); if (pageError) throw pageError; const { error: versionError } = await admin.from('website_page_versions').insert({ organization_id: organizationId, site_id: site.id, page_id: page.id, version_number: 1, document, created_by: user.id, change_summary: 'Initial draft' }); if (versionError) throw versionError; await audit(admin, organizationId, user.id, 'website.created', { site_id: site.id, slug }); return json({ success: true, site, page }, 201); }
    const siteId = String(body.siteId || ''); if (!siteId) return json({ success: false, error: 'siteId is required.' }, 400);
    if (operation === 'updateSite' || operation === 'archiveSite') { const patch = operation === 'archiveSite' ? { status: 'archived', archived_at: new Date().toISOString() } : { name: String(body.name || '').trim() }; if (operation === 'updateSite' && (!patch.name || patch.name.length > 120)) return json({ success: false, error: 'Website name is invalid.' }, 400); const { data, error } = await admin.from('website_sites').update(patch).eq('id', siteId).eq('organization_id', organizationId).select('id,name,slug,status,updated_at').maybeSingle(); if (error || !data) return json({ success: false, error: 'Website not found.' }, 404); await audit(admin, organizationId, user.id, operation === 'archiveSite' ? 'website.archived' : 'website.renamed', { site_id: siteId }); return json({ success: true, site: data }); }
    if (mutate) { const { data: activeSite } = await admin.from('website_sites').select('id').eq('id', siteId).eq('organization_id', organizationId).is('archived_at', null).maybeSingle(); if (!activeSite) return json({ success: false, error: 'Website not found or archived.' }, 404); }
    if (operation === 'listPages') { const { data, error } = await admin.from('website_pages').select('id,name,slug,page_type,is_homepage,updated_at,draft_version').eq('site_id', siteId).eq('organization_id', organizationId).order('sort_order'); if (error) throw error; return json({ success: true, pages: data || [] }); }
    if (operation === 'createPage') { const name = String(body.name || '').trim(); const slug = String(body.slug || ''); const pageType = ['standard', 'not_found'].includes(String(body.pageType)) ? body.pageType : 'standard'; if (!name || name.length > 120 || !/^\/[a-z0-9](?:[a-z0-9/-]{0,190}[a-z0-9])?$/.test(slug)) return json({ success: false, error: 'Page name or path is invalid.' }, 400); const document = { version: 1, sections: [] }; const { data: page, error } = await admin.from('website_pages').insert({ organization_id: organizationId, site_id: siteId, name, slug, page_type: pageType, draft_document: document, created_by: user.id }).select('*').single(); if (error) throw error; const { error: versionError } = await admin.from('website_page_versions').insert({ organization_id: organizationId, site_id: siteId, page_id: page.id, version_number: 1, document, created_by: user.id, change_summary: 'Initial draft' }); if (versionError) throw versionError; await audit(admin, organizationId, user.id, 'website.page_created', { site_id: siteId, page_id: page.id, slug }); return json({ success: true, page }, 201); }
    if (operation === 'getPageDocument') { const { data, error } = await admin.from('website_pages').select('id,draft_document,draft_version,updated_at').eq('id', body.pageId).eq('site_id', siteId).eq('organization_id', organizationId).maybeSingle(); if (error || !data) return json({ success: false, error: 'Page not found.' }, 404); return json({ success: true, page: data }); }
    if (operation === 'updatePageMetadata') { const name = String(body.name || '').trim(); if (!name || name.length > 120) return json({ success: false, error: 'Page name is invalid.' }, 400); const { data, error } = await admin.from('website_pages').update({ name, seo_title: body.seoTitle || null, seo_description: body.seoDescription || null }).eq('id', body.pageId).eq('site_id', siteId).eq('organization_id', organizationId).select('id,name,updated_at').maybeSingle(); if (error || !data) return json({ success: false, error: 'Page not found.' }, 404); await audit(admin, organizationId, user.id, 'website.page_renamed', { site_id: siteId, page_id: data.id }); return json({ success: true, page: data }); }
    if (operation === 'savePageDocument') { const document = validateDocument(body.document); const { data: current, error } = await admin.from('website_pages').select('draft_version').eq('id', body.pageId).eq('site_id', siteId).eq('organization_id', organizationId).maybeSingle(); if (error || !current) return json({ success: false, error: 'Page not found.' }, 404); if (body.expectedVersion !== undefined && Number(body.expectedVersion) !== current.draft_version) return json({ success: false, error: 'This page changed elsewhere. Reload before saving.' }, 409); const next = current.draft_version + 1; const { error: versionError } = await admin.from('website_page_versions').insert({ organization_id: organizationId, site_id: siteId, page_id: body.pageId, version_number: next, document, created_by: user.id, change_summary: typeof body.changeSummary === 'string' ? body.changeSummary.slice(0, 280) : null }); if (versionError) throw versionError; const { data, error: updateError } = await admin.from('website_pages').update({ draft_document: document, draft_version: next }).eq('id', body.pageId).eq('organization_id', organizationId).select('id,draft_version,updated_at').single(); if (updateError) throw updateError; await audit(admin, organizationId, user.id, 'website.page_document_saved', { site_id: siteId, page_id: body.pageId, version: next }); return json({ success: true, page: data }); }
    return json({ success: false, error: 'Unsupported website operation.' }, 400);
  } catch (error: any) { return json({ success: false, error: error.message || 'Unable to manage websites.' }, 400); }
});
