import { useRef, useState } from 'react';
import { ImagePlus, Trash2, Upload } from 'lucide-react';
import { Modal } from '../../components/common/Modal';
import { websiteBuilderService } from '../../services/websiteBuilderService';

type Asset = { id: string; file_name: string; mime_type: string; file_size: number; width?: number; height?: number; created_at: string; preview_url?: string };
const toBase64 = async (file: File) => { const bytes = new Uint8Array(await file.arrayBuffer()); let text = ''; bytes.forEach((byte) => { text += String.fromCharCode(byte); }); return btoa(text); };
export function MediaLibrary({ open, onClose, organizationId, siteId, assets, onAssets, onSelect }: { open: boolean; onClose: () => void; organizationId: string; siteId: string; assets: Asset[]; onAssets: (assets: Asset[]) => void; onSelect: (asset: Asset) => void }) {
  const input = useRef<HTMLInputElement>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const upload = async (file?: File) => { if (!file) return; if (!['image/png', 'image/jpeg', 'image/webp'].includes(file.type) || file.size > 10 * 1024 * 1024) { setError('Use a PNG, JPEG, or WebP image up to 10MB.'); return; } setBusy(true); setError(''); try { const result = await websiteBuilderService.uploadAsset({ organizationId, siteId, fileName: file.name, mimeType: file.type, fileBase64: await toBase64(file) }); onAssets([result.asset, ...assets]); } catch (reason: any) { setError(reason.message || 'Upload failed.'); } finally { setBusy(false); } };
  const remove = async (asset: Asset) => { setBusy(true); setError(''); try { await websiteBuilderService.deleteAsset(organizationId, siteId, asset.id); onAssets(assets.filter((item) => item.id !== asset.id)); } catch (reason: any) { setError(reason.message || 'Unable to delete image.'); } finally { setBusy(false); } };
  return <Modal isOpen={open} onClose={onClose} title="Media Library" subtitle="Private images for this website."><div className="space-y-4">{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<input ref={input} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={(event) => void upload(event.target.files?.[0])}/><button onClick={() => input.current?.click()} disabled={busy} className="inline-flex items-center gap-2 rounded-lg bg-blue-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><Upload className="h-4 w-4"/>{busy ? 'Working…' : 'Upload image'}</button>{assets.length ? <div className="grid max-h-[55vh] grid-cols-2 gap-3 overflow-y-auto sm:grid-cols-3">{assets.map((asset) => <article key={asset.id} className="group overflow-hidden rounded-xl border border-slate-200 bg-white"><button onClick={() => { onSelect(asset); onClose(); }} className="block w-full text-left"><img src={asset.preview_url} alt="" loading="lazy" className="h-28 w-full bg-slate-100 object-cover"/><span className="block truncate p-2 text-xs font-medium text-slate-700">{asset.file_name}</span></button><div className="flex items-center justify-between px-2 pb-2 text-[11px] text-slate-500"><span>{asset.width && asset.height ? `${asset.width}×${asset.height}` : asset.mime_type} · {Math.round(asset.file_size / 1024)}KB</span><button onClick={() => void remove(asset)} disabled={busy} className="rounded p-1 text-red-600 hover:bg-red-50" aria-label={`Delete ${asset.file_name}`}><Trash2 className="h-3.5 w-3.5"/></button></div></article>)}</div> : <div className="flex flex-col items-center gap-2 rounded-xl border border-dashed border-slate-300 px-6 py-12 text-center text-slate-500"><ImagePlus className="h-7 w-7 text-blue-600"/><p className="font-medium text-slate-800">Upload your first image</p><p className="text-sm">PNG, JPEG, or WebP up to 10MB.</p></div>}</div></Modal>;
}
