import { Image, LayoutPanelTop, Minus, MousePointer2, PanelBottom, Type, Wand2 } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type SectionType = 'hero' | 'text' | 'image' | 'button_group' | 'spacer' | 'header' | 'footer';
export type WebsiteSection = { id: string; type: SectionType; props: Record<string, any>; style: Record<string, any> };
export type WebsiteDocument = { version: 1; theme?: { primaryColor: string; backgroundColor: string; textColor: string; radius: 'sm' | 'md' | 'lg' }; sections: WebsiteSection[] };
export type NavigationItem = { id: string; label: string; pageId?: string; externalUrl?: string; visible: boolean };
export type GlobalSections = { version: 1; navigation: NavigationItem[]; header: WebsiteSection | null; footer: WebsiteSection | null };
type Definition = { type: SectionType; title: string; category: string; description: string; icon: LucideIcon; global?: boolean; defaults: Omit<WebsiteSection, 'id' | 'type'> };

export const websiteSectionRegistry: Definition[] = [
  { type: 'hero', title: 'Hero', category: 'Hero', description: 'A clear opening message with calls to action.', icon: Wand2, defaults: { props: { eyebrow: 'Welcome', heading: 'Build something memorable', subheading: 'Tell visitors why your business matters.', primaryLabel: 'Get started', primaryUrl: '#', secondaryLabel: 'Learn more', secondaryUrl: '#', alignment: 'center', minHeight: 420, backgroundAssetId: null, sideAssetId: null, overlayOpacity: 0.35, imageFit: 'cover' }, style: { backgroundColor: '#0f172a', textColor: '#ffffff' } } },
  { type: 'text', title: 'Text', category: 'Content', description: 'A focused heading and supporting copy.', icon: Type, defaults: { props: { heading: 'A thoughtful heading', body: 'Use this space to explain your value in clear, useful language.', alignment: 'left', maxWidth: 680 }, style: { backgroundColor: '#ffffff', textColor: '#0f172a', paddingY: 72 } } },
  { type: 'image', title: 'Image', category: 'Media', description: 'An image from your secure media library.', icon: Image, defaults: { props: { assetId: null, url: '', alt: 'Website image', width: 100, alignment: 'center', radius: 16, fit: 'cover' }, style: { backgroundColor: '#ffffff' } } },
  { type: 'button_group', title: 'Button group', category: 'CTA', description: 'A compact call-to-action group.', icon: MousePointer2, defaults: { props: { heading: 'Ready to begin?', buttons: [{ label: 'Get started', url: '#', variant: 'primary' }] }, style: { backgroundColor: '#f8fafc', textColor: '#0f172a', alignment: 'center' } } },
  { type: 'spacer', title: 'Spacer', category: 'Layout', description: 'Responsive breathing room between sections.', icon: Minus, defaults: { props: { desktop: 72, tablet: 48, mobile: 32 }, style: {} } },
  { type: 'header', title: 'Header', category: 'Navigation', description: 'A reusable navigation header for every page.', icon: LayoutPanelTop, global: true, defaults: { props: { siteName: '', logoAssetId: null, ctaLabel: '', ctaUrl: '#', sticky: false, variant: 'logo-left', mobileOpen: false }, style: { backgroundColor: '#ffffff', textColor: '#0f172a', transparent: false } } },
  { type: 'footer', title: 'Footer', category: 'Navigation', description: 'A reusable site footer for every page.', icon: PanelBottom, global: true, defaults: { props: { siteName: '', logoAssetId: null, description: 'A thoughtful website, built with NextAura.', copyright: '© Your business', socialLinks: [] }, style: { backgroundColor: '#0f172a', textColor: '#ffffff', variant: 'columns' } } },
];
export const sectionDefinition = (type: SectionType) => websiteSectionRegistry.find((item) => item.type === type)!;
export const newSection = (type: SectionType): WebsiteSection => { const definition = sectionDefinition(type); return { id: crypto.randomUUID(), type, props: structuredClone(definition.defaults.props), style: structuredClone(definition.defaults.style) }; };
const asset = (id: string | null | undefined, urls?: Record<string, string>) => id ? urls?.[id] : undefined;

export function WebsiteSectionRenderer({ section, device, selected, onSelect, chrome, assetUrls, navigation, onNavigate }: { section: WebsiteSection; device: 'desktop' | 'tablet' | 'mobile'; selected?: boolean; onSelect?: () => void; chrome?: boolean; assetUrls?: Record<string, string>; navigation?: NavigationItem[]; onNavigate?: (pageId: string) => void }) {
  const p = section.props; const s = section.style; const align = p.alignment || s.alignment || 'left'; const click = () => onSelect?.(); const frame = `${chrome ? 'cursor-pointer transition outline outline-1 outline-transparent hover:outline-blue-300' : ''} ${selected ? '!outline-2 !outline-blue-500' : ''}`; const navigate = (item: NavigationItem) => (event: React.MouseEvent) => { event.preventDefault(); if (item.pageId) onNavigate?.(item.pageId); };
  if (section.type === 'header') return <header onClick={click} className={`${frame} ${p.sticky ? 'sticky top-0 z-20' : ''} relative px-6 py-4`} style={{ background: s.transparent ? 'transparent' : s.backgroundColor, color: s.textColor }}><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><div className="flex items-center gap-2 font-semibold">{asset(p.logoAssetId, assetUrls) && <img src={asset(p.logoAssetId, assetUrls)} alt="" className="h-8 w-8 rounded object-contain"/>}{p.siteName}</div><nav className="hidden items-center gap-5 text-sm md:flex">{(navigation || []).filter((item) => item.visible).map((item) => <a key={item.id} href={item.externalUrl || '#'} onClick={navigate(item)}>{item.label}</a>)}</nav>{p.ctaLabel && <a href={p.ctaUrl} onClick={(event) => event.preventDefault()} className="rounded-lg bg-blue-700 px-3 py-2 text-sm font-semibold text-white">{p.ctaLabel}</a>}<button className="rounded p-2 md:hidden" aria-label="Open navigation">☰</button></div></header>;
  if (section.type === 'footer') return <footer onClick={click} className={`${frame} px-6 py-12`} style={{ background: s.backgroundColor, color: s.textColor }}><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 font-semibold">{asset(p.logoAssetId, assetUrls) && <img src={asset(p.logoAssetId, assetUrls)} alt="" className="h-8 w-8 rounded object-contain"/>}{p.siteName}</div><p className="mt-3 max-w-sm text-sm opacity-75">{p.description}</p></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-sm">{(navigation || []).filter((item) => item.visible).map((item) => <a key={item.id} href={item.externalUrl || '#'} onClick={navigate(item)}>{item.label}</a>)}</div></div><p className="mx-auto mt-10 max-w-6xl border-t border-white/20 pt-5 text-xs opacity-60">{p.copyright}</p></footer>;
  if (section.type === 'hero') { const background = asset(p.backgroundAssetId, assetUrls); const side = asset(p.sideAssetId, assetUrls); return <section onClick={click} className={`${frame} relative flex overflow-hidden px-8 py-12`} style={{ minHeight: p.minHeight, background: background ? `linear-gradient(rgb(15 23 42 / ${p.overlayOpacity || .35}), rgb(15 23 42 / ${p.overlayOpacity || .35})), url(${background}) center/${p.imageFit || 'cover'}` : s.backgroundColor, color: s.textColor, justifyContent: align === 'center' ? 'center' : align === 'right' ? 'flex-end' : 'flex-start', textAlign: align as any }}><div className="my-auto max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] opacity-70">{p.eyebrow}</p><h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-5xl">{p.heading}</h1><p className="mt-5 text-base leading-7 opacity-80">{p.subheading}</p><div className="mt-8 flex flex-wrap gap-3"><a href={p.primaryUrl} onClick={(e) => e.preventDefault()} className="rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-slate-900">{p.primaryLabel}</a>{p.secondaryLabel && <a href={p.secondaryUrl} onClick={(e) => e.preventDefault()} className="rounded-lg border border-white/40 px-4 py-2.5 text-sm font-semibold">{p.secondaryLabel}</a>}</div></div>{side && <img src={side} alt="" className="ml-8 hidden w-[38%] self-center rounded-2xl object-cover lg:block"/>}</section>; }
  if (section.type === 'text') return <section onClick={click} className={`${frame} px-8`} style={{ background: s.backgroundColor, color: s.textColor, paddingTop: s.paddingY, paddingBottom: s.paddingY, textAlign: align as any }}><div style={{ maxWidth: p.maxWidth, margin: align === 'center' ? 'auto' : align === 'right' ? '0 0 0 auto' : undefined }}><h2 className="text-3xl font-semibold tracking-tight">{p.heading}</h2><p className="mt-4 whitespace-pre-wrap text-base leading-7 opacity-80">{p.body}</p></div></section>;
  if (section.type === 'image') { const source = asset(p.assetId, assetUrls) || p.url; return <section onClick={click} className={`${frame} px-8 py-10`} style={{ background: s.backgroundColor, textAlign: p.alignment as any }}>{source ? <img src={source} alt={p.alt} style={{ width: `${p.width}%`, borderRadius: p.radius, objectFit: p.fit }} className="inline-block max-w-full"/> : <div className="rounded-xl border border-dashed border-slate-300 p-10 text-sm text-slate-500">Choose an image from Media Library</div>}</section>; }
  if (section.type === 'button_group') return <section onClick={click} className={`${frame} px-8 py-14`} style={{ background: s.backgroundColor, color: s.textColor, textAlign: s.alignment as any }}><h2 className="text-3xl font-semibold">{p.heading}</h2><div className="mt-6 flex flex-wrap gap-3" style={{ justifyContent: s.alignment === 'center' ? 'center' : s.alignment === 'right' ? 'flex-end' : 'flex-start' }}>{(p.buttons || []).map((button: any, index: number) => <a key={index} href={button.url} onClick={(e) => e.preventDefault()} className={`rounded-lg px-4 py-2.5 text-sm font-semibold ${button.variant === 'outline' ? 'border border-slate-400' : button.variant === 'secondary' ? 'bg-slate-200 text-slate-900' : 'bg-blue-700 text-white'}`}>{button.label}</a>)}</div></section>;
  return <div onClick={click} className={frame} style={{ height: p[device] ?? p.desktop }} />;
}
