import { Image, Minus, MousePointer2, Type, Wand2 } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type WebsiteSection = { id: string; type: 'hero' | 'text' | 'image' | 'button_group' | 'spacer'; props: Record<string, any>; style: Record<string, any> };
export type WebsiteDocument = { version: 1; theme?: { primaryColor: string; backgroundColor: string; textColor: string; radius: 'sm' | 'md' | 'lg' }; sections: WebsiteSection[] };
type Definition = { type: WebsiteSection['type']; title: string; category: string; description: string; icon: LucideIcon; defaults: Omit<WebsiteSection, 'id' | 'type'> };

export const websiteSectionRegistry: Definition[] = [
  { type: 'hero', title: 'Hero', category: 'Hero', description: 'A clear opening message with calls to action.', icon: Wand2, defaults: { props: { eyebrow: 'Welcome', heading: 'Build something memorable', subheading: 'Tell visitors why your business matters.', primaryLabel: 'Get started', primaryUrl: '#', secondaryLabel: 'Learn more', secondaryUrl: '#', alignment: 'center', minHeight: 420 }, style: { backgroundColor: '#0f172a', textColor: '#ffffff' } } },
  { type: 'text', title: 'Text', category: 'Content', description: 'A focused heading and supporting copy.', icon: Type, defaults: { props: { heading: 'A thoughtful heading', body: 'Use this space to explain your value in clear, useful language.', alignment: 'left', maxWidth: 680 }, style: { backgroundColor: '#ffffff', textColor: '#0f172a', paddingY: 72 } } },
  { type: 'image', title: 'Image', category: 'Media', description: 'An image with accessible alt text.', icon: Image, defaults: { props: { url: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=80', alt: 'Team collaborating', width: 100, alignment: 'center', radius: 16, fit: 'cover' }, style: { backgroundColor: '#ffffff' } } },
  { type: 'button_group', title: 'Button group', category: 'CTA', description: 'A compact call-to-action group.', icon: MousePointer2, defaults: { props: { heading: 'Ready to begin?', buttons: [{ label: 'Get started', url: '#', variant: 'primary' }] }, style: { backgroundColor: '#f8fafc', textColor: '#0f172a', alignment: 'center' } } },
  { type: 'spacer', title: 'Spacer', category: 'Layout', description: 'Responsive breathing room between sections.', icon: Minus, defaults: { props: { desktop: 72, tablet: 48, mobile: 32 }, style: {} } },
];
export const sectionDefinition = (type: WebsiteSection['type']) => websiteSectionRegistry.find((item) => item.type === type)!;
export const newSection = (type: WebsiteSection['type']): WebsiteSection => { const definition = sectionDefinition(type); return { id: crypto.randomUUID(), type, props: structuredClone(definition.defaults.props), style: structuredClone(definition.defaults.style) }; };
export function WebsiteSectionRenderer({ section, device, selected, onSelect, chrome }: { section: WebsiteSection; device: 'desktop' | 'tablet' | 'mobile'; selected?: boolean; onSelect?: () => void; chrome?: boolean }) {
  const p = section.props; const s = section.style; const align = p.alignment || s.alignment || 'left'; const click = () => onSelect?.(); const frame = `${chrome ? 'cursor-pointer transition outline outline-1 outline-transparent hover:outline-blue-300' : ''} ${selected ? '!outline-2 !outline-blue-500' : ''}`;
  if (section.type === 'hero') return <section onClick={click} className={`${frame} flex px-8 py-12`} style={{ minHeight: p.minHeight, background: s.backgroundColor, color: s.textColor, justifyContent: align === 'center' ? 'center' : align === 'right' ? 'flex-end' : 'flex-start', textAlign: align as any }}><div className="my-auto max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.2em] opacity-70">{p.eyebrow}</p><h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-5xl">{p.heading}</h1><p className="mt-5 text-base leading-7 opacity-80">{p.subheading}</p><div className="mt-8 flex flex-wrap gap-3"><a href={p.primaryUrl} onClick={(e) => e.preventDefault()} className="rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-slate-900">{p.primaryLabel}</a>{p.secondaryLabel && <a href={p.secondaryUrl} onClick={(e) => e.preventDefault()} className="rounded-lg border border-white/40 px-4 py-2.5 text-sm font-semibold">{p.secondaryLabel}</a>}</div></div></section>;
  if (section.type === 'text') return <section onClick={click} className={`${frame} px-8`} style={{ background: s.backgroundColor, color: s.textColor, paddingTop: s.paddingY, paddingBottom: s.paddingY, textAlign: align as any }}><div style={{ maxWidth: p.maxWidth, margin: align === 'center' ? 'auto' : align === 'right' ? '0 0 0 auto' : undefined }}><h2 className="text-3xl font-semibold tracking-tight">{p.heading}</h2><p className="mt-4 whitespace-pre-wrap text-base leading-7 opacity-80">{p.body}</p></div></section>;
  if (section.type === 'image') return <section onClick={click} className={`${frame} px-8 py-10`} style={{ background: s.backgroundColor, textAlign: p.alignment as any }}><img src={p.url} alt={p.alt} style={{ width: `${p.width}%`, borderRadius: p.radius, objectFit: p.fit }} className="inline-block max-w-full"/></section>;
  if (section.type === 'button_group') return <section onClick={click} className={`${frame} px-8 py-14`} style={{ background: s.backgroundColor, color: s.textColor, textAlign: s.alignment as any }}><h2 className="text-3xl font-semibold">{p.heading}</h2><div className="mt-6 flex flex-wrap gap-3" style={{ justifyContent: s.alignment === 'center' ? 'center' : s.alignment === 'right' ? 'flex-end' : 'flex-start' }}>{(p.buttons || []).map((button: any, index: number) => <a key={index} href={button.url} onClick={(e) => e.preventDefault()} className={`rounded-lg px-4 py-2.5 text-sm font-semibold ${button.variant === 'outline' ? 'border border-slate-400' : button.variant === 'secondary' ? 'bg-slate-200 text-slate-900' : 'bg-blue-700 text-white'}`}>{button.label}</a>)}</div></section>;
  return <div onClick={click} className={frame} style={{ height: p[device] ?? p.desktop }} />;
}
