import { newSection, type GlobalSections, type WebsiteDocument } from './sectionRegistry';

export type WebsiteTemplate = { id: string; name: string; category: string; description: string; theme: WebsiteDocument['theme']; globals: GlobalSections; sections: WebsiteDocument['sections'] };
const build = (id: string, name: string, category: string, description: string, types: Parameters<typeof newSection>[0][], theme: WebsiteDocument['theme']): WebsiteTemplate => ({ id, name, category, description, theme, globals: { version: 1, navigation: [], header: { ...newSection('header'), props: { ...newSection('header').props, siteName: name } }, footer: { ...newSection('footer'), props: { ...newSection('footer').props, siteName: name } } }, sections: types.map(newSection) });
export const websiteTemplates: WebsiteTemplate[] = [
  build('restaurant', 'Restaurant', 'Hospitality', 'A warm editorial menu, social proof, and an inviting booking path.', ['hero', 'features', 'services', 'stats', 'gallery', 'testimonials', 'contact'], { primaryColor: '#a16207', backgroundColor: '#fffbeb', textColor: '#292524', radius: 'md' }),
  build('agency', 'Agency', 'Professional services', 'A modern service story with process, proof, people, and a strong enquiry path.', ['hero', 'services', 'stats', 'features', 'testimonials', 'team', 'contact'], { primaryColor: '#2563eb', backgroundColor: '#f8fafc', textColor: '#0f172a', radius: 'md' }),
  build('saas', 'SaaS', 'Software', 'A concise product narrative with benefits, pricing, credibility, and answers.', ['hero', 'features', 'stats', 'pricing', 'testimonials', 'faq', 'button_group'], { primaryColor: '#4f46e5', backgroundColor: '#f8fafc', textColor: '#111827', radius: 'lg' }),
  build('portfolio', 'Personal Portfolio', 'Portfolio', 'A minimal project-led structure for independent creators and studios.', ['hero', 'stats', 'gallery', 'services', 'testimonials', 'contact'], { primaryColor: '#0f172a', backgroundColor: '#fafafa', textColor: '#111827', radius: 'sm' }),
  build('fitness', 'Fitness / Gym', 'Wellness', 'An energetic conversion path with programs, results, coaching, and membership options.', ['hero', 'services', 'stats', 'testimonials', 'pricing', 'team', 'contact'], { primaryColor: '#15803d', backgroundColor: '#f0fdf4', textColor: '#14532d', radius: 'lg' }),
  build('beauty', 'Beauty / Salon', 'Wellness', 'An elegant service and treatment experience with gallery-led social proof.', ['hero', 'services', 'gallery', 'testimonials', 'pricing', 'team', 'contact'], { primaryColor: '#be185d', backgroundColor: '#fff1f2', textColor: '#4a044e', radius: 'lg' }),
];
export const themePresets = [{ id: 'minimal', name: 'Minimal Light', theme: { primaryColor: '#2563eb', backgroundColor: '#ffffff', textColor: '#0f172a', radius: 'sm' as const } }, { id: 'dark', name: 'Modern Dark', theme: { primaryColor: '#818cf8', backgroundColor: '#0f172a', textColor: '#f8fafc', radius: 'md' as const } }, { id: 'warm', name: 'Warm Editorial', theme: { primaryColor: '#b45309', backgroundColor: '#fffaf0', textColor: '#292524', radius: 'md' as const } }, { id: 'bold', name: 'Bold Startup', theme: { primaryColor: '#4f46e5', backgroundColor: '#ffffff', textColor: '#111827', radius: 'lg' as const } }, { id: 'luxury', name: 'Elegant Luxury', theme: { primaryColor: '#a16207', backgroundColor: '#171717', textColor: '#fafaf9', radius: 'sm' as const } }, { id: 'wellness', name: 'Soft Wellness', theme: { primaryColor: '#15803d', backgroundColor: '#f7fee7', textColor: '#14532d', radius: 'lg' as const } }];
